name: 'Build snort3 package for aarch64'

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-package:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Checkout Entware 
        uses: actions/checkout@v3
        with:
          repository: Entware/Entware
          path: Entware

      - name: Setup local tools
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: build-essential automake ccache clang curl file g++-multilib gawk gcc-multilib gettext git libssl-dev libncurses5-dev locales mc procps pv pwgen python2-minimal python3 python3-pip rsync signify-openbsd subversion sudo unzip wget zlib1g-dev
          version: 1.0

      - name: Copy in our kernel 4.1 changes
        run: cp -af aarch64-4.1/* ./Entware

      - name: Set our config
        working-directory: ./Entware
        run: |
          make package/symlinks
          cp -v configs/aarch64-4.1.config .config
          make oldconfig

      - name: Restore toolchain cache      
        id: cache-toolchain-restore
        uses: actions/cache/restore@v3
        with:
          path: |
            ./Entware
          key: ${{ runner.OS }}-toolchain-cache

      - name: install tools
        working-directory: ./Entware
        run: |
          make -j4 tools/install 
        
      - name: install toolchain
        working-directory: ./Entware
        run: |
          make -j4 toolchain/install

      - name: toolchain cache
        id: cache-toolchain
        uses: actions/cache/save@v3
        with:
          path: |
            ./Entware
          key: ${{ steps.cache-toolchain-restore.outputs.cache-primary-key }}
          
      - name: patch paths for /opt
        working-directory: ./Entware
        run: |
          find feeds/packages -type f -not -path '*/\.*' -exec sed -i 's/^\/etc/\/opt\/etc/g' {} +
          find feeds/packages -type f -not -path '*/\.*' -exec sed -i 's/)\/etc/)\/opt\/etc/g' {} +
          find feeds/packages -type f -not -path '*/\.*' -exec sed -i 's/)\/usr/)\/opt/g' {} +

      - name: build openssl package
        working-directory: ./Entware
        run: |
          make -j4 package/openssl/compile

      - name: build snort package
        working-directory: ./Entware
        run: |
          make -j4 package/snort3/compile

      - name: Set release version
        id: version
        run: |
          echo "version=$(grep 'PKG_VERSION:' Entware/package/feeds/packages/snort3/Makefile|cut -d= -f2)" >> $GITHUB_OUTPUT

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: Snort {{ steps.version.outputs.version }} - {{ github.sha }}
          draft: true
          files: |
            Entware/bin/targets/aarch64-4.1/generic-glibc/packages/libdaq3*
            Entware/bin/targets/aarch64-4.1/generic-glibc/packages/libhwloc*
            Entware/bin/targets/aarch64-4.1/generic-glibc/packages/libopenssl*
            Entware/bin/targets/aarch64-4.1/generic-glibc/packages/libpciaccess*
            Entware/bin/targets/aarch64-4.1/generic-glibc/packages/libtirpc*
            Entware/bin/targets/aarch64-4.1/generic-glibc/packages/snort3*

